// <auto-generated />
namespace AccountingSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ChequeRakam_jornalEntries : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChequeRakam_jornalEntries));
        
        string IMigrationMetadata.Id
        {
            get { return "201812030403249_ChequeRakam_jornalEntries"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
